-- QR Codes Table (Back Office Database)
-- Stores QR codes generated by vendors/restaurants

CREATE TABLE IF NOT EXISTS qr_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid REFERENCES restaurants(id) ON DELETE CASCADE,
  vendor_id uuid REFERENCES vendors(id) ON DELETE CASCADE,
  
  -- QR code data
  qr_code_hash text NOT NULL UNIQUE, -- Unique hash/identifier for the QR code
  qr_code_data jsonb NOT NULL, -- Full QR code payload (JSON)
  
  -- Point configuration (set by admin)
  points_awarded integer DEFAULT 1 CHECK (points_awarded >= 0),
  
  -- Mascot drop configuration (set by admin)
  mascot_drop_enabled boolean DEFAULT false,
  mascot_drop_rate numeric(5,2) DEFAULT 0.0 CHECK (mascot_drop_rate >= 0 AND mascot_drop_rate <= 100), -- Percentage (0-100)
  collection_set_id uuid, -- Which collection set this QR code can drop mascots from (references collection_sets in main DB)
  
  -- Status and metadata
  status text DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'expired', 'suspended')),
  expires_at timestamptz,
  max_scans integer, -- Optional: limit number of scans per QR code
  current_scans integer DEFAULT 0,
  
  -- Generation metadata
  generated_by uuid REFERENCES profiles(id), -- Vendor/admin who generated it
  generated_at timestamptz DEFAULT now(),
  
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_qr_codes_hash ON qr_codes(qr_code_hash);
CREATE INDEX IF NOT EXISTS idx_qr_codes_restaurant ON qr_codes(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_qr_codes_vendor ON qr_codes(vendor_id);
CREATE INDEX IF NOT EXISTS idx_qr_codes_status ON qr_codes(status) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_qr_codes_collection_set ON qr_codes(collection_set_id) WHERE collection_set_id IS NOT NULL;

-- Comments
COMMENT ON TABLE qr_codes IS 'QR codes generated by vendors/restaurants for users to scan';
COMMENT ON COLUMN qr_codes.qr_code_hash IS 'Unique identifier for the QR code, used for validation';
COMMENT ON COLUMN qr_codes.qr_code_data IS 'Full JSON payload that is encoded in the QR code';
COMMENT ON COLUMN qr_codes.points_awarded IS 'Points awarded when this QR code is scanned (can be overridden by restaurant_point_configs)';
COMMENT ON COLUMN qr_codes.mascot_drop_rate IS 'Percentage chance (0-100) that a mascot will drop when scanned';

